name: Keep Streamlit App Awake

on:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch: # Allows you to run it manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit URL
        run: curl -s https://quiz-master-by-joe-v8hv3x7blqf35lgjpge6br.streamlit.app > /dev/null
